config/routes.rb
# encoding: utf-8
#
# Redmine plugin to preview an attachment inline
#
# Copyright © 2018 Stephan Wenzel <stephan.wenzel@drwpatent.de>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#

Rails.application.routes.draw do

  post 'attachments/view_inline/:id/:tag_id', :to => 'attachments#view_inline', :id => /\d+/, :tag_id => /[a-z0-9_]{1,65}/, :as => 'view_attachment_inline'

end

app/views/attachments/_attachment_iframe.html.erb
<script type="text/javascript">  
  function resizeIframe(obj) {
	obj.style.height = obj.contentWindow.document.body.scrollHeight + 'px';
  }
</script>
<iframe src="<%= named_attachment_url(@attachment, @attachment.filename, :view_inline => 'true') %>" style="width: 100%; height: 16px;" seamless="seamless" scrolling="no" frameborder="0" allowtransparency="true" onload="resizeIframe(this);">
</iframe>	

app/views/attachments/_attachment_object_embed.html.erb
<script type="text/javascript">  
  function resizeObject(obj) {
    obj.style.height = obj.scrollHeight + 'px';
    console.log(obj.scrollHeight + 'px');
  }
</script>
<object data="<%= named_attachment_url(@attachment, @attachment.filename, :view_inline => 'true') %>" id='<%= @new_tag_id %>' style="width: 100%; height: 16px;" seamless="seamless" scrolling="no" frameborder="0" allowtransparency="true" onload="resizeObject(this);" type="text/html" title="<%= @attachment.filename %>">
  <embed href="<%= named_attachment_url(@attachment, @attachment.filename, :view_inline => 'true') %>" type="text/html" onload="resizeObject(this);">
</object>   

app/views/attachments/_links.html.erb
<div class="attachments">
<div class="contextual">
  <%= link_to(l(:label_edit_attachments),
              container_attachments_edit_path(container),
              :title => l(:label_edit_attachments),
              :class => 'icon-only icon-edit'
             ) if options[:editable] %>
</div>
<table style="width:100%;">
<% for attachment in attachments %>
<% preview_row_id    = SecureRandom.uuid.to_s.gsub(/\-/, "_") %>
<% preview_tag_id    = SecureRandom.uuid.to_s.gsub(/\-/, "_") %>
<tr>
  <td>
    <%= link_to_attachment attachment, class: 'icon-only icon-download icon-download-custom', title: l(:button_download), download: true -%>
    <%= link_to_attachment attachment, class: 'icon icon-attachment' -%>
    <span class="icon icon-magnifier icon-magnifier-custom" onclick="<%= "$.ajax({url:'#{view_attachment_inline_path(attachment.id, preview_tag_id)}', type: 'post'}); $('##{preview_row_id}').toggle();".html_safe %>">
    	<span class="size">(<%= number_to_human_size attachment.filesize %>)</span>
    </span>
  </td>
  <td><%= attachment.description unless attachment.description.blank? %></td>
  <td>
    <% if options[:author] %>
      <span class="author"><%= attachment.author %>, <%= format_time(attachment.created_on) %></span>
    <% end %>
  </td>
  <td>
    <% if options[:deletable] %>
      <%= link_to l(:button_delete), attachment_path(attachment),
                  :data => {:confirm => l(:text_are_you_sure)},
                  :method => :delete,
                  :class => 'delete icon-only icon-del',
                  :title => l(:button_delete) %>
    <% end %>
  </td>
  <td></td>
</tr>
<tr id="<%= preview_row_id %>" style="display:none;">
  <td colspan="5">
    <div class="box">
      <span class="icon icon-close" onclick="<%= "$('##{preview_row_id}').hide(); $('##{preview_tag_id}').html('');".html_safe %>"></span>
      <div id="<%= preview_tag_id %>">
      </div>
    </div>
  </td>
</tr>
<% end %>
</table>
<% if defined?(thumbnails) && thumbnails %>
  <% images = attachments.select(&:thumbnailable?) %>
  <% if images.any? %>
  <div class="thumbnails">
    <% images.each do |attachment| %>
      <% preview_pane_id   = SecureRandom.uuid.to_s.gsub(/\-/, "_") %>
      <% preview_tag_id    = SecureRandom.uuid.to_s.gsub(/\-/, "_") %>
      <%- if Setting['plugin_redmine_preview_inline']['fullwidth'].to_i == 1 %>
          <div><%= thumbnail_tag(attachment, :no_inner_view_pane => true, :preview_pane_id => preview_pane_id, :preview_tag_id => preview_tag_id) %></div>
          <%= render :partial => 'attachments/thumbnail_inline_view_pane', :locals => {:attachment => attachment, :preview_tag_id => preview_tag_id, :preview_pane_id => preview_pane_id, :width_param => "100%" } %>
      <%- else %>
        <div><%= thumbnail_tag(attachment) %></div>
      <%- end %>
    <% end %>
  </div>
  <% end %>
<% end %>
</div>

app/views/attachments/_thumbnail_inline_preview.html.erb
<% preview_row_id    = SecureRandom.uuid.to_s.gsub(/\-/, "_") %>
<% preview_tag_id    = SecureRandom.uuid.to_s.gsub(/\-/, "_") %>
<span class="icon icon-magnifier" onclick="<%= "$.ajax({url:'#{view_attachment_inline_path(attachment.id, preview_tag_id)}', type: 'post'}); $('##{preview_row_id}').toggle();".html_safe %>"></span>
<table id="<%= preview_row_id %>" style="display:none;" width="<%= json_escape(Setting['plugin_redmine_preview_inline']['size']).presence || "300" %>">
  <tbody>
	<tr>
	  <td class="box" style="text-align:left;">
		<span class="icon icon-close" onclick="<%= "$('##{preview_row_id}').hide(); $('##{preview_tag_id}').html('');".html_safe %>"></span>
		<br>
		<div id="<%= preview_tag_id %>" style="width:100%;"></div>
	  </td>
	</tr>
  </tbody>
</table>

app/views/attachments/_thumbnail_inline_view_pane.html.erb
<table class="box" id="<%= preview_pane_id %>" style="display:none;" width="<%= width_param %>">
  <tbody>
    <tr>
      <td style="text-align:left;">
        <span class="icon icon-close" onclick="<%= "$('##{preview_pane_id}').hide(); $('##{preview_tag_id}').html('');".html_safe %>"></span>
        <br>
        <span id="<%= preview_tag_id %>" style="width:100%"></span>
      </td>
    </tr>
  </tbody>
</table>

app/views/attachments/_thumbnail_inline_view_selector.html.erb
<span class="icon icon-magnifier" onclick="<%= "$.ajax({url:'#{view_attachment_inline_path(attachment.id, preview_tag_id)}', type: 'post'}); $('##{preview_pane_id}').toggle();".html_safe %>"></span>

app/views/attachments/view_inline.js.erb
$('#<%= @tag_id %>').html('<%= escape_javascript @content %>')

app/views/issues/_history.html.erb
<% reply_links = issue.notes_addable? -%>
<% for journal in journals %>
  <div id="change-<%= journal.id %>" class="<%= journal.css_classes %>">
    <div id="note-<%= journal.indice %>">
    <h4><a href="#note-<%= journal.indice %>" class="journal-link">#<%= journal.indice %></a>
    <%= avatar(journal.user, :size => "24") %>
    <%= authoring journal.created_on, journal.user, :label => :label_updated_time_by %>
    <%= render_private_notes_indicator(journal) %></h4>

    <% if journal.details.any? %>
    <ul class="details">
      <% details_to_strings(journal.visible_details).each do |string| %>
       <li><%= string %></li>
      <% end %>
    </ul>
    <% if Setting.thumbnails_enabled? && (thumbnail_attachments = journal_thumbnail_attachments(journal)).any? %>
      <div class="thumbnails">
        <% thumbnail_attachments.each do |attachment| %>
		  <% preview_pane_id   = SecureRandom.uuid.to_s.gsub(/\-/, "_") %>
		  <% preview_tag_id    = SecureRandom.uuid.to_s.gsub(/\-/, "_") %>
		  <%- if Setting['plugin_redmine_preview_inline']['fullwidth'].to_i == 1 %>
			  <div><%= thumbnail_tag(attachment, :no_inner_view_pane => true, :preview_pane_id => preview_pane_id, :preview_tag_id => preview_tag_id) %></div>
			  <%= render :partial => 'attachments/thumbnail_inline_view_pane', :locals => {:attachment => attachment, :preview_tag_id => preview_tag_id, :preview_pane_id => preview_pane_id, :width_param => "100%"  } %>
		  <%- else %>
			<div><%= thumbnail_tag(attachment) %></div>
		  <%- end %>
        <% end %>
      </div>
    <% end %>
    <% end %>
    <%= render_notes(issue, journal, :reply_links => reply_links) unless journal.notes.blank? %>
    </div>
  </div>
  <%= call_hook(:view_issues_history_journal_bottom, { :journal => journal }) %>
<% end %>

<% heads_for_wiki_formatter if User.current.allowed_to?(:edit_issue_notes, issue.project) || User.current.allowed_to?(:edit_own_issue_notes, issue.project) %>

app/views/layouts/view_attachment_inline.html.erb
<!DOCTYPE html>
<html lang="<%= current_language %>">
<head>
<meta charset="utf-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge"/>
<title><%= html_title %></title>
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
<meta name="description" content="<%= Redmine::Info.app_name %>" />
<meta name="keywords" content="issue,bug,tracker" />
<%= csrf_meta_tag %>
<%= favicon %>
<%= stylesheet_link_tag 'jquery/jquery-ui-1.13.2', 'application', 'responsive', :media => 'all' %>
<%= stylesheet_link_tag 'rtl', :media => 'all' if l(:direction) == 'rtl' %>
<%= javascript_heads %>
<%= heads_for_theme %>
<%= call_hook :view_layouts_base_html_head %>
<!-- page specific tags -->
<%= yield :header_tags -%>
</head>
<body class="<%= body_css_classes %>">
  <%= call_hook :view_layouts_base_body_top %>
  <div id="wrapper">
    <div id="wrapper2">
      <div id="wrapper3">
        <div id="nosidebar">
            <%= render_flash_messages %>
            <%= yield %>
            <%= call_hook :view_layouts_base_content %>
            <div style="clear:both;"></div>
        </div>
      </div>
    </div>
  </div>
  <%= call_hook :view_layouts_base_body_bottom %>
</body>
</html>

app/views/settings/redmine_preview_inline/_settings.html.erb
<fieldset class="box tabular settings"><legend><%= l(:text_preview_inline_size_setting) %></legend>
  <p>
	<label><%= l(:text_preview_inline_fullwidth)  %></label>
	<%= check_box_tag 'settings[fullwidth]', '1', (settings['fullwidth'].to_i == 1) %>
  </p>
  <p>
	<label><%= l(:text_preview_inline_size_setting)  %></label>
	<%= text_field_tag 'settings[size]', settings["size"], :id => "preview_size_setting", :maxlength => 10, :placeholder => json_escape( settings["size"]) %>
  </p>
</fieldset>